'''
Filetypes created specifically for this project, which are usually
generated by one or more scripts as output and accepted by one or
more scripts as input.

The word "filetype" is used loosely here; many of these formats are
simply json-serialized structures or some other common container
type (but *what* is stored of course varies between formats!)
'''
from . import graph
from . import gpos
from . import cycles

